spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/andres-cloud-services/config-files.git

  http:
    encoding:
      charset: UTF-8

  jmx:
    default-domain: ${spring.application.name}

server:
  port: 8888